name: 'GitHub Action to create a "release pull request"'
description: 'Create a "release pull request" that contains features list or pull requests.'
author: 'Yutaro Muta'
inputs:
  token:
    description: 'Token for GitHub API'
    required: true
  repository:
    description: 'The owner and repository name. For example, octocat/Hello-World.'
  production-branch:
    description: 'The branch name that is deployed in production environment.'
    default: 'main'
  staging-branch:
    description: 'The branch name that the feature branches are merged into and is going to be merged into the "production" branch.'
    default: 'develop'
  label:
    description: 'Label for adding to pull requests created. If not specified, any labels will not be added for pull requests.'
  draft:
    description: 'Create a pull request as a draft.'
    default: false
  dry-run:
    description: 'Do not create/update a pull request. Just prints out.'
    default: false
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'git-pull-request'
  color: 'white'
