name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  test_ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install
      run: |
        npm install
    - name: lint
      run: |
        npm run lint
    - name: build
      run: |
        npm run build
    - name: test
      run: |
        npm run test
      env:
        TEST_TOKEN: ${{ github.token }}
        TEST_REPOSITORY: ${{ github.repository }}
        TEST_PRODUCTION_BRANCH: ${{ secrets.GITHUB_PRODUCTION_BRANCH }}
        TEST_STAGING_BRANCH: ${{ secrets.GITHUB_STAGING_BRANCH }}
        TEST_REPOSITORY_ID: ${{ secrets.GITHUB_REPOSITORY_ID }}
        TEST_PULL_REQUEST_ID: ${{ secrets.GITHUB_PULL_REQUEST_ID }}
        TEST_COMMIT_SHA: ${{ secrets.GITHUB_COMMIT_SHA}}
        TEST_PULL_REQUEST_NUMBER: ${{ secrets.GITHUB_REQUEST_NUMBER }}
